name: Demo-Java-deployment

on:
  workflow_dispatch:

jobs: 
  deploy:
    name: Java-App
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        
      - name: Package-Java-app 
        run: |
          echo "Start the Build"
          mvn -f Project/TurkishAirlines/build.xml package
          echo "Package complete."
